# 130服务器bug记录

报错：

```
Traceback (most recent call last):
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/disk4t/Archived/221101/PYC130/code/fewmmdetection/mmdet/models/detectors/mask_rcnn.py", line 27, in __init__
    init_cfg=init_cfg)
  File "/disk4t/Archived/221101/PYC130/code/fewmmdetection/mmdet/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/disk4t/Archived/221101/PYC130/code/fewmmdetection/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dims'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 219, in <module>
    main()
  File "tools/train.py", line 192, in main
    test_cfg=cfg.get('test_cfg'))
  File "/disk4t/Archived/221101/PYC130/code/fewmmdetection/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dims'

```

